# Generated by Django 4.2.2 on 2023-08-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('augalas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pikiavimo_data', models.DateTimeField(blank=True, null=True)),
                ('persodinimo_vieta', models.CharField(max_length=100)),
                ('augalo_uzsodinimo_plotas', models.CharField(help_text='nurodyti skaičių arais', max_length=100, verbose_name='augalo užsodinimo plotas')),
                ('derliaus_nuemimo_data', models.DateTimeField(blank=True, null=True, verbose_name='derliaus nuėmimo data')),
                ('derliaus_kiekis', models.TextField(max_length=100)),
                ('derliaus_sandeliavimo_vieta', models.CharField(max_length=225, verbose_name='derliaus sandėliavimo vieta')),
                ('derliaus_laikymo_laikotarpis', models.CharField(blank=True, help_text='nurodyti kiek laiko laikėsi derlius', max_length=225, null=True)),
                ('augalas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='augalas.augalas')),
            ],
            options={
                'verbose_name': 'Darzas',
                'verbose_name_plural': 'Daržas',
            },
        ),
        migrations.CreateModel(
            name='DarzoDarbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Darzo Darbas',
                'verbose_name_plural': 'Daržo Darbai',
            },
        ),
        migrations.CreateModel(
            name='DarzoPrieziura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('augalu_prieziuros_data', models.DateTimeField(blank=True, null=True, verbose_name='augalų priežiūros data')),
                ('augalu_prieziuros_informacija', models.TextField(blank=True, max_length=255, null=True, verbose_name='Parašykite kokią atlikote augalų priežiūrą, laistymas, tręšimas, genėjimas....')),
                ('pastabos', models.TextField(blank=True, max_length=255, null=True)),
                ('darzas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darzas.darzas')),
                ('darzodarbas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darzas.darzodarbas')),
            ],
            options={
                'verbose_name': 'Darzo Prieziura',
                'verbose_name_plural': 'Daržo Priežiūra',
            },
        ),
    ]
