# Generated by Django 4.2.2 on 2023-09-05 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('darzas', '0003_alter_darzas_augalas_alter_darzoderlius_augalas'),
    ]

    operations = [
        migrations.AddField(
            model_name='darzodarbas',
            name='naudotojas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
