# Generated by Django 4.2.2 on 2023-09-05 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('augalas', '0004_alter_augalas_veisle'),
        ('darzas', '0004_darzodarbas_naudotojas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darzas',
            name='augalas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='augalas.augalas'),
        ),
        migrations.AlterField(
            model_name='darzodarbas',
            name='pavadinimas',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='darzoderlius',
            name='augalas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='augalas.augalas'),
        ),
        migrations.AlterUniqueTogether(
            name='darzodarbas',
            unique_together={('pavadinimas', 'naudotojas')},
        ),
    ]
