# Generated by Django 4.2.2 on 2023-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Augalas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(help_text='Sėklos, Daigai, Gėlių sėklos, Sodinukai ir t.t', max_length=50)),
                ('pavadinimas', models.CharField(help_text='Nurodykite augalo pavadinimą, pvz... agurkai, morkos ir t.t', max_length=50)),
                ('veisle', models.CharField(help_text='Nurodykite augalo veislę', max_length=255, verbose_name='veislė')),
                ('kiekis', models.IntegerField()),
                ('talpos_dydis', models.CharField(blank=True, help_text='Vazono talpa, pvz O,5 litro, 2 litrai', max_length=50, null=True)),
                ('sejimo_arba_sodinimo_data', models.DateTimeField(verbose_name='sėjimo - sodinimo data')),
                ('sejimo_arba_sodinimo_vieta', models.CharField(max_length=120, verbose_name='sėjimo - sodinimo vieta')),
                ('zemiu_rusis', models.CharField(blank=True, max_length=120, null=True, verbose_name='žemių rūšis')),
                ('laistymo_budas', models.CharField(help_text='kapiliarinis laistymas, laistymas iš šlangos ir t.t. ', max_length=225, verbose_name='laistymo būdas')),
                ('pastabos', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'augalas',
                'verbose_name_plural': 'Augalai',
            },
        ),
    ]
