# Generated by Django 4.2.2 on 2023-08-31 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('augalas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='augalas',
            name='naudotojas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
