# Generated by Django 4.2.2 on 2023-08-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augalas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augalas',
            name='sejimo_arba_sodinimo_vieta',
            field=models.CharField(max_length=120, verbose_name='sėjimo - sodinimo vieta'),
        ),
    ]
