# Generated by Django 4.2.2 on 2023-09-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augalas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='augalas',
            name='nuotrauka',
            field=models.ImageField(blank=True, null=True, upload_to='augalo_nuotraukos'),
        ),
    ]
