# Generated by Django 4.2.2 on 2023-09-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augalas', '0003_augalas_nuotrauka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augalas',
            name='veisle',
            field=models.CharField(help_text='Nurodykite augalo veislę', max_length=255, unique=True, verbose_name='veislė'),
        ),
    ]
