# Generated by Django 4.2.2 on 2023-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augalas', '0005_alter_augalas_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augalas',
            name='veisle',
            field=models.CharField(help_text='Nurodykite augalo veislę', max_length=255, verbose_name='veislė'),
        ),
    ]
